name: REST Assured tests
on:
  push:
    branches: [main]
jobs:
  test-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'oracle'
          java-version: '21'

      - name: Run Tests
        run: mvn surefire-report:report

      - name: Rename Report
        run: mv ./target/site/surefire-report.html ./target/site/index.html

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: surefire-report
          path: target/site

      - uses: JamesIves/github-pages-deploy-action@v4
        if: always()
        with:
          branch: gh-pages
          folder: target/site
